const characters = [
  // ===== イナズマイレブン（1作目） =====
  { id:1,  name:"円堂守",       kana:"えんどうまもる",       team:"雷門中学校",       pos:"GK", series:"1", element:"土", number:1,  hissatsu:["神の手","マジン・ザ・ハンド","いかりのてっつい","ゴッドキャッチ"] },
  { id:2,  name:"豪炎寺修也",   kana:"ごうえんじしゅうや",   team:"雷門中学校",       pos:"FW", series:"1", element:"火", number:10, hissatsu:["ファイアトルネード","爆熱ストーム","ファイアトルネードDD"] },
  { id:3,  name:"鬼道有人",     kana:"きどうゆうと",         team:"帝国学園",         pos:"MF", series:"1", element:"風", number:14, hissatsu:["皇帝ペンギン2号","ジ・イカロス"] },
  { id:4,  name:"風丸一郎太",   kana:"かぜまるいちろうた",   team:"雷門中学校",       pos:"DF", series:"1", element:"風", number:2,  hissatsu:["ザ・タワー","ハリケーンアロー"] },
  { id:5,  name:"壁山塔子",     kana:"かべやまとうこ",       team:"雷門中学校",       pos:"DF", series:"1", element:"土", number:2,  hissatsu:["ザ・ウォール"] },
  { id:6,  name:"染岡竜吾",     kana:"そめおかりゅうご",     team:"雷門中学校",       pos:"FW", series:"1", element:"火", number:9,  hissatsu:["ドラゴンクラッシュ","ドラゴンスレイヤー","ワイバーンクラッシュ"] },
  { id:7,  name:"栗松鉄平",     kana:"くりまつてっぺい",     team:"雷門中学校",       pos:"MF", series:"1", element:"土", number:4,  hissatsu:["ローリングキック"] },
  { id:8,  name:"半田真一",     kana:"はんだしんいち",       team:"雷門中学校",       pos:"DF", series:"1", element:"土", number:5,  hissatsu:["コイルターン"] },
  { id:9,  name:"松野空介",     kana:"まつのくうすけ",       team:"雷門中学校",       pos:"MF", series:"1", element:"風", number:6,  hissatsu:["バックトルネード"] },
  { id:10, name:"宍戸佐吉",     kana:"ししどさきち",         team:"雷門中学校",       pos:"MF", series:"1", element:"土", number:7,  hissatsu:["グラビテイション"] },
  { id:11, name:"影野仁",       kana:"かげのじん",           team:"雷門中学校",       pos:"MF", series:"1", element:"風", number:8,  hissatsu:["インビジブルショット"] },
  { id:12, name:"少林寺歩",     kana:"しょうりんじあゆむ",   team:"雷門中学校",       pos:"MF", series:"1", element:"木", number:3,  hissatsu:["カンフーヘッド"] },
  { id:13, name:"目金欠流",     kana:"めがねかける",         team:"雷門中学校",       pos:"MF", series:"1", element:"木", number:11, hissatsu:["めがねクラッシュ"] },
  { id:14, name:"吹雪士郎",     kana:"ふぶきしろう",         team:"白恋中学校",       pos:"FW", series:"1", element:"風", number:10, hissatsu:["エターナルブリザード","ウルフレジェンド","ザ・バース"] },
  { id:15, name:"吹雪アツヤ",   kana:"ふぶきあつや",         team:"白恋中学校",       pos:"FW", series:"1", element:"風", number:10, hissatsu:["エターナルブリザード"] },
  { id:16, name:"佐久間次郎",   kana:"さくまじろう",         team:"帝国学園",         pos:"FW", series:"1", element:"闇", number:9,  hissatsu:["皇帝ペンギン2号","ツインブースト"] },
  { id:17, name:"源田幸次郎",   kana:"げんだこうじろう",     team:"帝国学園",         pos:"GK", series:"1", element:"土", number:1,  hissatsu:["パワーシールド"] },
  { id:18, name:"不動明王",     kana:"ふどうあきお",         team:"真帝国学園",       pos:"FW", series:"1", element:"火", number:10, hissatsu:["皇帝ペンギン3号"] },
  { id:19, name:"寺門大貴",     kana:"てらかどだいき",       team:"帝国学園",         pos:"DF", series:"1", element:"土", number:3,  hissatsu:["パワーブロック"] },
  { id:20, name:"基山タツヤ",   kana:"もとやまたつや",       team:"雷門中学校",       pos:"MF", series:"1", element:"火", number:12, hissatsu:["イリュージョンボール"] },
  { id:21, name:"飛鷹征矢",     kana:"とびたかせいや",       team:"雷門中学校",       pos:"FW", series:"1", element:"木", number:13, hissatsu:["シュートポケット"] },
  { id:22, name:"綱海条介",     kana:"つなみじょうすけ",     team:"雷門中学校",       pos:"DF", series:"1", element:"土", number:15, hissatsu:["ザ・テュフォン","つなみブースト"] },
  { id:23, name:"一之瀬一哉",   kana:"いちのせかずや",       team:"雷門中学校",       pos:"MF", series:"1", element:"風", number:16, hissatsu:["フレイムダンス","ザ・フェニックス"] },
  { id:24, name:"立向居勇気",   kana:"たちむかいゆうき",     team:"雷門中学校",       pos:"GK", series:"1", element:"木", number:20, hissatsu:["真マジン・ザ・ハンド"] },
  { id:25, name:"土門飛鳥",     kana:"どもんあすか",         team:"雷門中学校",       pos:"DF", series:"1", element:"木", number:17, hissatsu:["キラースライド","ツインブースト"] },
  { id:26, name:"木暮夕弥",     kana:"こぐれゆうや",         team:"雷門中学校",       pos:"MF", series:"1", element:"闇", number:18, hissatsu:["うしろのしょうめんだーれ"] },
  { id:27, name:"ヒロト",       kana:"ひろと",               team:"エイリア学園",     pos:"FW", series:"1", element:"火", number:10, hissatsu:["天空落とし","ライジングスラッシュ"] },
  { id:28, name:"グラン",       kana:"ぐらん",               team:"エイリア学園",     pos:"MF", series:"1", element:"火", number:10, hissatsu:["スーパーノヴァ"] },
  { id:29, name:"デザーム",     kana:"でざーむ",             team:"エイリア学園",     pos:"GK", series:"1", element:"闇", number:1,  hissatsu:["ガニメデプロトン"] },
  { id:30, name:"レーゼ",       kana:"れーぜ",               team:"エイリア学園",     pos:"FW", series:"1", element:"闇", number:11, hissatsu:["アストロブレイク"] },
  { id:31, name:"涼野風介",     kana:"すずのふうすけ",       team:"雷門中学校",       pos:"MF", series:"1", element:"風", number:19, hissatsu:["ノーザンインパクト"] },
  { id:32, name:"亜風炉照美",   kana:"あふろてるみ",         team:"雷門中学校",       pos:"MF", series:"1", element:"火", number:21, hissatsu:["グランフェンリルII"] },

  // ===== イナズマイレブン GO =====
  { id:33, name:"松風天馬",     kana:"まつかぜてんま",       team:"新雷門中学校",     pos:"MF", series:"GO", element:"風", number:8,  hissatsu:["マッハウィンド","そよかぜステップ","神風ドリブル"] },
  { id:34, name:"剣城京介",     kana:"つるぎきょうすけ",     team:"新雷門中学校",     pos:"FW", series:"GO", element:"闇", number:10, hissatsu:["デスソード","ロストエンジェル","デスドロップ"] },
  { id:35, name:"神童拓人",     kana:"しんどうたくと",       team:"新雷門中学校",     pos:"MF", series:"GO", element:"風", number:9,  hissatsu:["フォルテシモ","ハーモニクス"] },
  { id:36, name:"西園信助",     kana:"にしぞのしんすけ",     team:"新雷門中学校",     pos:"GK", series:"GO", element:"土", number:1,  hissatsu:["バーニングキャッチ","魔神ザ・ハンド"] },
  { id:37, name:"霧野蘭丸",     kana:"きりのらんまる",       team:"新雷門中学校",     pos:"DF", series:"GO", element:"風", number:3,  hissatsu:["ザ・ミスト","パワースパイク"] },
  { id:38, name:"狩屋マサキ",   kana:"かりやまさき",         team:"新雷門中学校",     pos:"DF", series:"GO", element:"闇", number:4,  hissatsu:["ハンターズネット","デッドストレート"] },
  { id:39, name:"倉間典人",     kana:"くらまのりひと",       team:"新雷門中学校",     pos:"FW", series:"GO", element:"木", number:11, hissatsu:["サイドワインダー"] },
  { id:40, name:"速水鶴正",     kana:"はやみつるまさ",       team:"新雷門中学校",     pos:"MF", series:"GO", element:"風", number:5,  hissatsu:["スピニングフェンス"] },
  { id:41, name:"浜野海士",     kana:"はまのかいし",         team:"新雷門中学校",     pos:"DF", series:"GO", element:"土", number:6,  hissatsu:["アトランティスウォール"] },
  { id:42, name:"天城大地",     kana:"あまぎだいち",         team:"新雷門中学校",     pos:"DF", series:"GO", element:"土", number:2,  hissatsu:["アトランティスウォール","ディープジャングル"] },
  { id:43, name:"三国太一",     kana:"みくにたいち",         team:"新雷門中学校",     pos:"GK", series:"GO", element:"土", number:1,  hissatsu:["バーニングキャッチ"] },
  { id:44, name:"錦龍馬",       kana:"にしきりょうま",       team:"新雷門中学校",     pos:"FW", series:"GO", element:"木", number:11, hissatsu:["ライディングショット"] },
  { id:45, name:"聖帝ツルギ",   kana:"せいていつるぎ",       team:"ゼロ",             pos:"FW", series:"GO", element:"闇", number:10, hissatsu:["エクスカリバー","ソードオブファイア"] },
  { id:46, name:"白竜",         kana:"はくりゅう",           team:"ゼロ",             pos:"FW", series:"GO", element:"風", number:9,  hissatsu:["ホワイトハリケーン"] },

  // ===== イナズマイレブン GO クロノ・ストーン =====
  { id:47, name:"フェイ・ルーン",     kana:"ふぇいるーん",           team:"テンマーズ",    pos:"MF", series:"CS", element:"木", number:7,  hissatsu:["オウジャノヒラメキ","ミキシマックス"] },
  { id:48, name:"ザナーク・アバロニク", kana:"ざなーくあばろにく",     team:"ザナークドメイン", pos:"FW", series:"CS", element:"火", number:11, hissatsu:["グレートマックスナ・オレ","ディザスターブレイク"] },
  { id:49, name:"アルファ",     kana:"あるふぁ",               team:"プロトコルオメガ", pos:"FW", series:"CS", element:"木", number:10, hissatsu:["シュートコマンド24"] },
  { id:50, name:"ベータ",       kana:"べーた",                 team:"プロトコルオメガ2.0", pos:"FW", series:"CS", element:"闇", number:10, hissatsu:["シュートコマンド06"] },
  { id:51, name:"ガンマ",       kana:"がんま",                 team:"プロトコルオメガ3.0", pos:"FW", series:"CS", element:"火", number:10, hissatsu:["シュートコマンド07"] },
  { id:52, name:"SARU",         kana:"さる",                   team:"フェーダ",         pos:"FW", series:"CS", element:"闇", number:10, hissatsu:["シェルビットバースト"] },
  { id:53, name:"ギリス",       kana:"ぎりす",                 team:"フェーダ",         pos:"MF", series:"CS", element:"木", number:8,  hissatsu:["リーサルスラッシュ"] },

  // ===== イナズマイレブン GO ギャラクシー =====
  { id:54, name:"瞬木隼人",     kana:"またたぎはやと",         team:"イナズマジャパン(Galaxy)", pos:"FW", series:"Galaxy", element:"風", number:10, hissatsu:["スターリングバード"] },
  { id:55, name:"鉄角真",       kana:"てっかくしん",           team:"イナズマジャパン(Galaxy)", pos:"DF", series:"Galaxy", element:"土", number:5,  hissatsu:["アイアンウォール"] },
  { id:56, name:"真名部陣一郎", kana:"まなべじんいちろう",     team:"イナズマジャパン(Galaxy)", pos:"MF", series:"Galaxy", element:"木", number:6,  hissatsu:["スパークリングウェイブ"] },
  { id:57, name:"皆帆和人",     kana:"みなほかずと",           team:"イナズマジャパン(Galaxy)", pos:"MF", series:"Galaxy", element:"土", number:7,  hissatsu:["アシストバトン"] },
  { id:58, name:"森村好葉",     kana:"もりむらこのは",         team:"イナズマジャパン(Galaxy)", pos:"MF", series:"Galaxy", element:"木", number:8,  hissatsu:["ラフレシアスマイル"] },
  { id:59, name:"市川座名九郎", kana:"いちかわざなくろう",     team:"イナズマジャパン(Galaxy)", pos:"FW", series:"Galaxy", element:"火", number:9,  hissatsu:["歌舞伎シュート"] },
  { id:60, name:"井吹宗正",     kana:"いぶきむねまさ",         team:"イナズマジャパン(Galaxy)", pos:"GK", series:"Galaxy", element:"風", number:1,  hissatsu:["ワイルドダンク","デュアルスマッシュ"] },
  { id:61, name:"九坂隆二",     kana:"くさかりゅうじ",         team:"イナズマジャパン(Galaxy)", pos:"FW", series:"Galaxy", element:"火", number:11, hissatsu:["バウンサーラビット"] },
  { id:62, name:"鶴見伊知郎",   kana:"つるみいちろう",         team:"イナズマジャパン(Galaxy)", pos:"DF", series:"Galaxy", element:"土", number:4,  hissatsu:["モアイブロック"] },
];
